<?php
session_start();
unset(
$_SESSION["infoPersonalSolicitada"],
$_SESSION["infoMedidasSolicitada"],
$_SESSION["infoBomberilSolicitada"],
$_SESSION["infoLaboralSolicitada"],
$_SESSION["infoMedica1Solicitada"],
$_SESSION["infoMedica2Solicitada"],
$_SESSION["infoFamiliarSolicitada"],
$_SESSION["infoAcademicaSolicitada"],
$_SESSION["infoEntrenamientoEstandarSolicitada"],
$_SESSION["infoHistoricaSolicitada"],
$_SESSION["infoCargosSolicitada"],
$_SESSION['idDeBomberoMasReciente'],
$_SESSION["idAModificar"]
);

?>
